using Tippy.App.Models;

namespace Tippy.App.Services;

public static class ApplicationShortcutCatalog
{
    public static IReadOnlyList<ApplicationShortcutProfile> Create() =>
    [
        P("Microsoft Word", "Microsoft", "Office", "Microsoft 365 / Office 2024 for Windows", "https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-word-95ef89dd-7142-4b50-afb2-f762f663ceb2",
            ("Bold", "Ctrl+B", "Apply or remove bold"), ("Italic", "Ctrl+I", "Apply or remove italic"), ("Underline", "Ctrl+U", "Apply or remove underline"),
            ("Bulleted list", "Ctrl+Shift+L", "Apply the default bullet list"), ("Heading 1", "Ctrl+Alt+1", "Apply Heading 1"), ("Heading 2", "Ctrl+Alt+2", "Apply Heading 2"),
            ("Normal style", "Ctrl+Shift+N", "Apply Normal style"), ("Show formatting marks", "Ctrl+Shift+8", "Show or hide nonprinting characters"),
            ("Insert page break", "Ctrl+Enter", "Insert a manual page break"), ("Insert hyperlink", "Ctrl+K", "Open the Insert Hyperlink dialog"),
            ("Insert comment", "Ctrl+Alt+M", "Add a new comment"), ("Track changes", "Ctrl+Shift+E", "Turn change tracking on or off"),
            ("Change letter case", "Shift+F3", "Cycle selected text through letter cases"), ("Repeat last action", "F4", "Repeat the previous command"),
            ("Insert footnote", "Ctrl+Alt+F", "Insert a footnote"), ("Insert endnote", "Ctrl+Alt+D", "Insert an endnote"),
            ("Go to", "Ctrl+G", "Open the Go To tab"), ("Move to document start", "Ctrl+Home", "Go to the beginning"), ("Move to document end", "Ctrl+End", "Go to the end")),

        P("Microsoft Excel", "Microsoft", "Office", "Microsoft 365 / Office 2024 for Windows", "https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f",
            ("Edit active cell", "F2", "Edit the active cell and place the insertion point at the end"), ("Format cells", "Ctrl+1", "Open Format Cells"),
            ("Create table", "Ctrl+T", "Create a table from the selected range"), ("Toggle filters", "Ctrl+Shift+L", "Add or remove AutoFilter"),
            ("AutoSum", "Alt+=", "Insert the SUM function"), ("Current date", "Ctrl+;", "Enter the current date"), ("Current time", "Ctrl+Shift+;", "Enter the current time"),
            ("New line in cell", "Alt+Enter", "Start a new line in the same cell"), ("Fill down", "Ctrl+D", "Fill the selected range downward"), ("Fill right", "Ctrl+R", "Fill the selected range rightward"),
            ("Next worksheet", "Ctrl+PageDown", "Move to the next sheet"), ("Previous worksheet", "Ctrl+PageUp", "Move to the previous sheet"),
            ("New worksheet", "Shift+F11", "Insert a new worksheet"), ("Show formulas", "Ctrl+`", "Show or hide formulas"),
            ("Toggle absolute reference", "F4", "Cycle formula references through absolute and relative forms"), ("Flash Fill", "Ctrl+E", "Invoke Flash Fill"),
            ("Select current region", "Ctrl+Shift+8", "Select the current data region"), ("Calculate workbook", "F9", "Calculate all open workbooks"),
            ("Calculate active sheet", "Shift+F9", "Calculate the active worksheet")),

        P("Microsoft PowerPoint", "Microsoft", "Office", "Microsoft 365 / Office 2024 for Windows", "https://support.microsoft.com/en-us/office/use-keyboard-shortcuts-to-create-powerpoint-presentations-ebb3d20e-dcd4-444f-a38e-bb5c5ed180f4",
            ("New slide", "Ctrl+M", "Insert a new slide"), ("Duplicate selection", "Ctrl+D", "Duplicate the selected object or slide"),
            ("Start slide show", "F5", "Start from the beginning"), ("Start from current slide", "Shift+F5", "Start from the current slide"),
            ("Presenter View", "Alt+F5", "Start the presentation in Presenter View"), ("Black screen", "B", "Show or hide a black screen during presentation"),
            ("White screen", "W", "Show or hide a white screen during presentation"), ("Group objects", "Ctrl+G", "Group selected objects"),
            ("Ungroup objects", "Ctrl+Shift+G", "Ungroup selected objects"), ("Bring forward", "Ctrl+Shift+]", "Move selected object forward"),
            ("Send backward", "Ctrl+Shift+[", "Move selected object backward"), ("Promote paragraph", "Alt+Shift+Left", "Promote a list paragraph"),
            ("Demote paragraph", "Alt+Shift+Right", "Demote a list paragraph"), ("Show guides", "Alt+F9", "Show or hide drawing guides"),
            ("Show grid", "Shift+F9", "Show or hide the grid"), ("Insert hyperlink", "Ctrl+K", "Insert a hyperlink")),

        P("Microsoft Outlook", "Microsoft", "Office", "Classic and new Outlook for Windows", "https://support.microsoft.com/en-us/office/keyboard-shortcuts-for-outlook-3cdeb221-7ae5-4c1d-8c1d-9e63216c1efd",
            ("New message", "Ctrl+Shift+M", "Create a new email message"), ("Reply", "Ctrl+R", "Reply to the sender"), ("Reply all", "Ctrl+Shift+R", "Reply to everyone"),
            ("Forward", "Ctrl+F", "Forward the selected message"), ("Send", "Alt+S", "Send the current message"), ("Check names", "Ctrl+K", "Resolve recipient names"),
            ("Go to Mail", "Ctrl+1", "Switch to Mail"), ("Go to Calendar", "Ctrl+2", "Switch to Calendar"), ("Go to Contacts", "Ctrl+3", "Switch to People"),
            ("Go to Tasks", "Ctrl+4", "Switch to Tasks"), ("Go to Inbox", "Ctrl+Shift+I", "Open the Inbox"), ("Go to Outbox", "Ctrl+Shift+O", "Open the Outbox"),
            ("Mark as read", "Ctrl+Q", "Mark the selected message as read"), ("Mark as unread", "Ctrl+U", "Mark the selected message as unread"),
            ("Flag message", "Insert", "Add or remove a follow-up flag"), ("Go to date", "Ctrl+G", "Open Go To Date in Calendar"),
            ("Search", "Ctrl+E", "Move focus to Search"), ("Send and receive all", "F9", "Send and receive all folders")),

        P("Microsoft OneNote", "Microsoft", "Office", "Microsoft 365 desktop OneNote for Windows", "https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-onenote-44b8b3f4-c274-4bcc-a089-e80fdcc87950",
            ("New page", "Ctrl+N", "Create a new page"), ("New page below", "Ctrl+Alt+N", "Create a page below the current page"),
            ("New subpage", "Ctrl+Shift+Alt+N", "Create a subpage"), ("Quick note", "Win+Alt+N", "Open a new Quick Note"),
            ("Checkbox tag", "Ctrl+1", "Apply or clear the To Do tag"), ("Important tag", "Ctrl+2", "Apply or clear the Important tag"),
            ("Question tag", "Ctrl+3", "Apply or clear the Question tag"), ("Clear note tags", "Ctrl+0", "Remove note tags"),
            ("Insert current date", "Alt+Shift+D", "Insert today's date"), ("Insert current time", "Alt+Shift+T", "Insert the current time"),
            ("Insert date and time", "Alt+Shift+F", "Insert current date and time"), ("Create Outlook task today", "Ctrl+Shift+5", "Create a Today Outlook task"),
            ("Sync current notebook", "Shift+F9", "Synchronize the current shared notebook"), ("Sync all notebooks", "F9", "Synchronize all shared notebooks"),
            ("Lock protected sections", "Ctrl+Alt+L", "Lock all password-protected sections")),

        P("Microsoft Access", "Microsoft", "Office", "Access 2024 / Microsoft 365 for Windows", "https://support.microsoft.com/en-us/office/keyboard-shortcuts-for-access-70a673e4-4f7b-4300-b8e5-3320fa6606e2",
            ("Navigation Pane", "F11", "Show or hide the Navigation Pane"), ("Cycle panes", "F6", "Cycle through panes in the workspace"),
            ("Property sheet", "F4", "Show or hide the property sheet"), ("Build dialog", "Ctrl+F2", "Open the Builder for the selected property"),
            ("Zoom box", "Shift+F2", "Open the Zoom box for a field or expression"), ("Visual Basic Editor", "Alt+F11", "Open the Visual Basic Editor"),
            ("Immediate window", "Ctrl+G", "Open the Immediate window in VBA"), ("Current date", "Ctrl+;", "Insert the current date"),
            ("Current time", "Ctrl+Shift+;", "Insert the current time"), ("Copy previous field value", "Ctrl+'", "Insert the value from the same field in the previous record"),
            ("Save As", "F12", "Open Save As"), ("Switch Form view", "Ctrl+Enter", "Switch between Design and Form view")),

        P("Microsoft Visio", "Microsoft", "Office", "Visio 2024 / Microsoft 365 for Windows", "https://support.microsoft.com/en-us/office/keyboard-shortcuts-for-visio-ee952f31-7e3e-4564-8116-f3ecbb733cc1",
            ("Pointer tool", "Ctrl+1", "Select the Pointer Tool"), ("Text tool", "Ctrl+2", "Select the Text Tool"), ("Connector tool", "Ctrl+3", "Select the Connector Tool"),
            ("Bring to front", "Ctrl+Shift+F", "Bring selected shape to front"), ("Send to back", "Ctrl+Shift+B", "Send selected shape to back"),
            ("Group", "Ctrl+G", "Group selected shapes"), ("Ungroup", "Ctrl+Shift+U", "Ungroup selected shapes"), ("Duplicate", "Ctrl+D", "Duplicate selected shapes"),
            ("Open ShapeSheet", "Ctrl+F9", "Open the ShapeSheet for the selected shape"), ("Fit page to window", "Ctrl+Shift+W", "Fit the page in the drawing window"),
            ("Drawing Explorer", "Ctrl+Shift+E", "Show or hide Drawing Explorer")),

        P("Microsoft Project", "Microsoft", "Office", "Project desktop for Windows", "https://support.microsoft.com/en-us/office/keyboard-shortcuts-for-project-7a4dc22b-ceb8-4a97-ac6f-6f9eaf36414a",
            ("Insert task", "Insert", "Insert a new task"), ("Delete task", "Delete", "Delete the selected task"),
            ("Indent task", "Alt+Shift+Right", "Indent the selected task"), ("Outdent task", "Alt+Shift+Left", "Outdent the selected task"),
            ("Link tasks", "Ctrl+F2", "Link selected tasks"), ("Unlink tasks", "Ctrl+Shift+F2", "Unlink selected tasks"),
            ("Go to selected task", "Ctrl+Shift+F5", "Scroll the timescale to the selected task"), ("Go to", "F5", "Open the Go To dialog"),
            ("Task information", "Shift+F2", "Open Task Information"), ("Assign resources", "Alt+F10", "Open Assign Resources"),
            ("Show subtasks", "Alt+Shift+=", "Show subtasks"), ("Hide subtasks", "Alt+Shift+-", "Hide subtasks")),

        P("Microsoft Teams", "Microsoft", "Communication", "New Teams for Windows", "https://support.microsoft.com/en-us/office/keyboard-shortcuts-for-microsoft-teams-2e8e2a70-e8d8-4a19-949b-4c36dd5292d2",
            ("Search", "Ctrl+E", "Move focus to Search"), ("New chat", "Ctrl+N", "Start a new chat"), ("Commands", "Ctrl+/", "Show available commands"),
            ("Keyboard shortcuts", "Ctrl+.", "Show keyboard shortcuts"), ("Go to chat", "Ctrl+2", "Open Chat"), ("Go to calendar", "Ctrl+4", "Open Calendar"),
            ("Mute microphone", "Ctrl+Shift+M", "Toggle microphone mute"), ("Toggle camera", "Ctrl+Shift+O", "Turn camera on or off"),
            ("Raise hand", "Ctrl+Shift+K", "Raise or lower your hand"), ("Start audio call", "Ctrl+Shift+C", "Start an audio call"),
            ("Start video call", "Ctrl+Shift+U", "Start a video call"), ("Accept audio call", "Ctrl+Shift+S", "Accept an incoming audio call")),

        P("Microsoft Publisher", "Microsoft", "Office", "Publisher for Microsoft 365 / Publisher 2021 on Windows", "https://support.microsoft.com/en-us/publisher/keyboard-shortcuts-in-publisher",
            ("New publication", "Ctrl+N", "Create a new publication"), ("Open publication", "Ctrl+O", "Open a publication"), ("Close publication", "Ctrl+W", "Close the current publication"),
            ("Find", "F3", "Open Find and Replace with Find selected"), ("Replace", "Ctrl+H", "Open Find and Replace with Replace selected"),
            ("Check spelling", "F7", "Check spelling"), ("Thesaurus", "Shift+F7", "Open the Thesaurus"), ("Show special characters", "Ctrl+Shift+Y", "Show or hide special characters"),
            ("Copy formatting", "Ctrl+Shift+C", "Copy selected text formatting"), ("Paste formatting", "Ctrl+Shift+V", "Apply copied formatting"),
            ("Superscript", "Ctrl+Shift+=", "Apply or remove superscript"), ("Subscript", "Ctrl+=", "Apply or remove subscript"),
            ("Bring to front", "Alt+F6", "Bring selected object to front"), ("Send to back", "Alt+Shift+F6", "Send selected object to back"),
            ("Group/ungroup", "Ctrl+Shift+G", "Group selected objects or ungroup a group"), ("Actual size", "F9", "Toggle actual-size view"),
            ("Full page", "Ctrl+Shift+L", "Zoom to full-page view"), ("Go to page", "F5", "Open Go To Page"),
            ("Previous page", "Ctrl+PageUp", "Go to previous page"), ("Next page", "Ctrl+PageDown", "Go to next page"),
            ("Macros", "Alt+F8", "Open the Macros dialog"), ("Visual Basic Editor", "Alt+F11", "Open Visual Basic Editor")),

        P("GIMP", "GIMP Team", "Creative", "GIMP 3 default Windows shortcuts", "https://docs.gimp.org/3.0/en/gimp-concepts-shortcuts.html",
            ("Rectangle Select", "R", "Activate Rectangle Select"), ("Ellipse Select", "E", "Activate Ellipse Select"), ("Free Select", "F", "Activate Free Select"),
            ("Move tool", "M", "Activate Move"), ("Crop tool", "Shift+C", "Activate Crop"), ("Paintbrush", "P", "Activate Paintbrush"),
            ("Pencil", "N", "Activate Pencil"), ("Eraser", "Shift+E", "Activate Eraser"), ("Gradient", "G", "Activate Gradient"),
            ("Clone", "C", "Activate Clone"), ("Text", "T", "Activate Text"), ("Paths", "B", "Activate Paths"),
            ("New layer", "Ctrl+Shift+N", "Create a new layer"), ("Duplicate layer", "Ctrl+Shift+D", "Duplicate the active layer"),
            ("Select none", "Ctrl+Shift+A", "Clear the selection"), ("Invert selection", "Ctrl+I", "Invert the current selection"),
            ("Fit image in window", "Ctrl+Shift+J", "Fit the image in the window"), ("Toggle docks", "Tab", "Hide or show docks")),

        P("Blender", "Blender Foundation", "3D / Creative", "Blender 4.x Industry-compatible concepts; default keymap may vary", "https://docs.blender.org/manual/en/latest/interface/keymap/introduction.html",
            ("Object/Edit mode", "Tab", "Toggle Edit Mode"), ("Move", "G", "Grab or move selection"), ("Rotate", "R", "Rotate selection"), ("Scale", "S", "Scale selection"),
            ("Add", "Shift+A", "Open the Add menu"), ("Duplicate", "Shift+D", "Duplicate selection"), ("Delete", "X", "Delete selection"),
            ("Search commands", "F3", "Open Operator Search"), ("Shading pie", "Z", "Open viewport shading pie"), ("Join objects", "Ctrl+J", "Join selected objects"),
            ("Set parent", "Ctrl+P", "Parent selected objects"), ("Clear parent", "Alt+P", "Clear parent relationship"),
            ("Front view", "Numpad1", "Switch to front view"), ("Side view", "Numpad3", "Switch to side view"), ("Top view", "Numpad7", "Switch to top view"),
            ("Perspective/orthographic", "Numpad5", "Toggle perspective and orthographic view"), ("Frame selected", "Decimal", "Frame selected in viewport"),
            ("Maximize area", "Ctrl+Space", "Maximize or restore the active editor"), ("Recalculate normals", "Shift+N", "Recalculate normals outside in Edit Mode")),

        P("Adobe Photoshop", "Adobe", "Creative", "Current Photoshop default Windows shortcuts", "https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html",
            ("Move tool", "V", "Select Move tool"), ("Marquee", "M", "Select Marquee tools"), ("Lasso", "L", "Select Lasso tools"), ("Object selection", "W", "Select object/quick selection tools"),
            ("Crop", "C", "Select Crop tool"), ("Eyedropper", "I", "Select Eyedropper"), ("Brush", "B", "Select Brush"), ("Clone Stamp", "S", "Select Clone Stamp"),
            ("Eraser", "E", "Select Eraser"), ("Gradient", "G", "Select Gradient/Paint Bucket"), ("Pen", "P", "Select Pen"), ("Type", "T", "Select Type tool"),
            ("Hand", "H", "Select Hand tool"), ("Zoom", "Z", "Select Zoom tool"), ("Step backward", "Ctrl+Alt+Z", "Step backward through history"),
            ("New layer", "Ctrl+Shift+N", "Create a new layer"), ("Duplicate layer", "Ctrl+J", "Duplicate selection to a layer"),
            ("Merge visible", "Ctrl+Shift+E", "Merge visible layers"), ("Stamp visible", "Ctrl+Shift+Alt+E", "Stamp visible layers to a new layer"),
            ("Image size", "Ctrl+Alt+I", "Open Image Size"), ("Canvas size", "Ctrl+Alt+C", "Open Canvas Size"),
            ("Keyboard shortcuts editor", "Ctrl+Shift+Alt+K", "Open Keyboard Shortcuts and Menus")),

        P("Adobe Illustrator", "Adobe", "Creative", "Current Illustrator default Windows shortcuts", "https://helpx.adobe.com/illustrator/using/default-keyboard-shortcuts.html",
            ("Selection tool", "V", "Select the Selection tool"), ("Direct Selection", "A", "Select the Direct Selection tool"), ("Magic Wand", "Y", "Select Magic Wand"),
            ("Lasso", "Q", "Select Lasso"), ("Pen", "P", "Select Pen"), ("Type", "T", "Select Type tool"), ("Line Segment", "\\", "Select Line Segment tool"),
            ("Rectangle", "M", "Select Rectangle tool"), ("Ellipse", "L", "Select Ellipse tool"), ("Paintbrush", "B", "Select Paintbrush"),
            ("Pencil", "N", "Select Pencil"), ("Rotate", "R", "Select Rotate tool"), ("Reflect", "O", "Select Reflect tool"), ("Scale", "S", "Select Scale tool"),
            ("Gradient", "G", "Select Gradient tool"), ("Eyedropper", "I", "Select Eyedropper"), ("Blend", "W", "Select Blend tool"), ("Artboard", "Shift+O", "Select Artboard tool"),
            ("Reapply transform", "Ctrl+D", "Repeat the last transformation"), ("Move dialog", "Ctrl+Shift+M", "Open Move dialog"),
            ("Transform Each", "Ctrl+Shift+Alt+D", "Open Transform Each"), ("Make clipping mask", "Ctrl+7", "Make a clipping mask"),
            ("Release clipping mask", "Ctrl+Alt+7", "Release a clipping mask"), ("Swap fill/stroke", "Shift+X", "Swap current fill and stroke"),
            ("Default fill/stroke", "D", "Set default fill and stroke"), ("Create outlines", "Ctrl+Shift+O", "Convert selected type to outlines"),
            ("Add fill", "Ctrl+/", "Add a new fill"), ("Add stroke", "Ctrl+Alt+/", "Add a new stroke"),
            ("Show hidden characters", "Ctrl+Alt+I", "Show or hide hidden characters")),

        P("Adobe Premiere Pro", "Adobe", "Video", "Current Premiere default Windows shortcuts", "https://helpx.adobe.com/premiere-pro/using/keyboard-shortcuts.html",
            ("Selection tool", "V", "Select the Selection tool"), ("Track Select Forward", "A", "Select clips forward on a track"), ("Ripple Edit", "B", "Select Ripple Edit tool"),
            ("Rolling Edit", "N", "Select Rolling Edit tool"), ("Rate Stretch", "R", "Select Rate Stretch tool"), ("Razor", "C", "Select Razor tool"),
            ("Slip", "Y", "Select Slip tool"), ("Slide", "U", "Select Slide tool"), ("Pen", "P", "Select Pen tool"), ("Hand", "H", "Select Hand tool"),
            ("Play/stop", "Space", "Toggle playback"), ("Shuttle left", "J", "Play backward or increase reverse speed"), ("Shuttle stop", "K", "Stop shuttle"), ("Shuttle right", "L", "Play forward or increase speed"),
            ("Mark In", "I", "Set an In point"), ("Mark Out", "O", "Set an Out point"), ("Clear In and Out", "Ctrl+Shift+X", "Clear both In and Out points"),
            ("Add edit", "Ctrl+K", "Add an edit at the playhead"), ("Add edit all tracks", "Ctrl+Shift+K", "Add edits on all targeted tracks"),
            ("Export Media", "Ctrl+M", "Open Export mode"), ("Keyboard shortcuts", "Ctrl+Alt+K", "Open Keyboard Shortcuts")),

        P("Adobe After Effects", "Adobe", "Motion graphics", "Current After Effects default Windows shortcuts", "https://helpx.adobe.com/after-effects/using/keyboard-shortcuts-reference.html",
            ("Selection tool", "V", "Activate Selection tool"), ("Hand tool", "H", "Activate Hand tool"), ("Zoom tool", "Z", "Activate Zoom tool"),
            ("Rotation tool", "W", "Activate Rotation tool"), ("Pan Behind tool", "Y", "Activate Pan Behind"), ("Pen tool", "G", "Activate Pen tool"),
            ("Text tool", "Ctrl+T", "Activate Horizontal Type tool"), ("New composition", "Ctrl+N", "Create a composition"),
            ("Composition settings", "Ctrl+K", "Open Composition Settings"), ("Split layer", "Ctrl+Shift+D", "Split selected layers"),
            ("Duplicate", "Ctrl+D", "Duplicate selected layers or effects"), ("Pre-compose", "Ctrl+Shift+C", "Pre-compose selected layers"),
            ("Time remapping", "Ctrl+Alt+T", "Enable time remapping"), ("Reveal position", "P", "Show Position property"), ("Reveal scale", "S", "Show Scale property"),
            ("Reveal rotation", "R", "Show Rotation property"), ("Reveal opacity", "T", "Show Opacity property"), ("Reveal audio", "L", "Show Audio Levels"),
            ("Easy Ease", "F9", "Apply Easy Ease to selected keyframes"), ("Add marker", "Multiply", "Add a composition marker")),

        P("Autodesk Maya", "Autodesk", "3D / Creative", "Maya 2025–2026 default hotkey set", "https://help.autodesk.com/cloudhelp/2025/ENU/Maya-KeyboardShortcuts/files/GUID-30CACC9D-8FBE-4B85-8A8F-C5ADF32DDD4E.htm",
            ("Select tool", "Q", "Activate Select tool"), ("Move tool", "W", "Activate Move tool"), ("Rotate tool", "E", "Activate Rotate tool"), ("Scale tool", "R", "Activate Scale tool"),
            ("Last used tool", "Y", "Select the last non-transform tool"), ("Repeat last action", "G", "Repeat the last action"),
            ("Object/component mode", "F8", "Toggle object and component selection"), ("Set key", "S", "Set a keyframe"),
            ("Key translate", "Shift+W", "Set a Translate key"), ("Key rotate", "Shift+E", "Set a Rotate key"), ("Key scale", "Shift+R", "Set a Scale key"),
            ("Hide selection", "Ctrl+H", "Hide selected objects"), ("Show selection", "Shift+H", "Show selected objects"), ("Show last hidden", "Ctrl+Shift+H", "Show the last hidden objects"),
            ("Wireframe", "4", "Use wireframe shading"), ("Shaded", "5", "Use shaded display"), ("Textured", "6", "Use shaded and textured display"), ("Use all lights", "7", "Use all scene lights"),
            ("Frame all", "A", "Frame all in active panel"), ("Frame selected", "F", "Frame selection in active panel"),
            ("Fullscreen panel", "Ctrl+Space", "Toggle current panel full screen"), ("Attribute Editor/Channel Box", "Ctrl+A", "Switch Attribute Editor and Channel Box"),
            ("Undo view", "[", "Undo the last view change"), ("Redo view", "]", "Redo the last view change"), ("Cycle background", "Alt+B", "Cycle viewport background color")),

        P("Autodesk 3ds Max", "Autodesk", "3D / Creative", "3ds Max 2024–2026 default hotkeys", "https://help.autodesk.com/cloudhelp/2024/ENU/3DSMax-Basics/files/GUID-AA36F53A-96A9-49A9-B66E-58A13AA788F9.htm",
            ("Select", "Q", "Activate Select Object"), ("Move", "W", "Activate Select and Move"), ("Rotate", "E", "Activate Select and Rotate"), ("Scale", "R", "Activate Select and Scale"),
            ("Material Editor", "M", "Open Material Editor"), ("Render setup", "F10", "Open Render Setup"), ("Render frame", "F9", "Render the current frame"),
            ("Wireframe", "F3", "Toggle wireframe and shaded view"), ("Edged faces", "F4", "Toggle edged faces"), ("Safe frames", "Shift+F", "Toggle safe frames"),
            ("Show statistics", "7", "Toggle viewport statistics"), ("Maximize viewport", "Alt+W", "Maximize or restore active viewport"),
            ("Top view", "T", "Switch active viewport to Top"), ("Front view", "F", "Switch active viewport to Front"), ("Left view", "L", "Switch active viewport to Left"),
            ("Perspective view", "P", "Switch active viewport to Perspective"), ("Camera view", "C", "Switch active viewport to Camera"),
            ("Zoom extents all", "Shift+Ctrl+Z", "Zoom extents in all viewports"), ("Angle snap", "A", "Toggle angle snap"), ("Percent snap", "Shift+Ctrl+P", "Toggle percent snap")),

        P("Ableton Live", "Ableton", "DAW / Music", "Live 12 default Windows shortcuts", "https://www.ableton.com/en/manual/live-keyboard-shortcuts/",
            ("Play/stop", "Space", "Play from start marker or stop"), ("Continue playback", "Shift+Space", "Continue from the stop point"), ("Record", "F9", "Toggle arrangement recording"),
            ("Session/Arrangement", "Tab", "Toggle Session and Arrangement views"), ("Device/Clip view", "Shift+Tab", "Toggle Device and Clip view"),
            ("Hot-swap", "Q", "Toggle Hot-Swap Mode"), ("Browser", "Ctrl+Alt+B", "Show or hide Browser"), ("Mixer", "Ctrl+Alt+M", "Show or hide Mixer"),
            ("Split clip", "Ctrl+E", "Split clip at selection"), ("Consolidate", "Ctrl+J", "Consolidate selection into a clip"), ("Crop clips", "Ctrl+Shift+J", "Crop selected clips"),
            ("Create fade", "Ctrl+Alt+F", "Create a fade or crossfade"), ("Toggle loop", "Ctrl+L", "Toggle loop brace"), ("Duplicate time", "Ctrl+Shift+D", "Duplicate selected time"),
            ("Insert audio track", "Ctrl+T", "Insert an audio track"), ("Insert MIDI track", "Ctrl+Shift+T", "Insert a MIDI track"), ("Insert return track", "Ctrl+Alt+T", "Insert a return track"),
            ("Group tracks", "Ctrl+G", "Group selected tracks"), ("Ungroup tracks", "Ctrl+Shift+G", "Ungroup selected tracks"),
            ("MIDI Map Mode", "Ctrl+M", "Toggle MIDI mapping"), ("Key Map Mode", "Ctrl+K", "Toggle key mapping"), ("Computer MIDI keyboard", "M", "Toggle computer MIDI keyboard"),
            ("Full screen", "F11", "Toggle Full Screen Mode"), ("Second window", "Ctrl+Shift+W", "Toggle second window")),

        P("Reason", "Reason Studios", "DAW / Music", "Reason 12–14 Windows key commands", "https://docs.reasonstudios.com/reason12/key-commands",
            ("Main Mixer", "F5", "Maximize or restore Main Mixer"), ("Rack", "F6", "Maximize or restore Rack"), ("Sequencer", "F7", "Maximize or restore Sequencer"),
            ("Detach Main Mixer", "Ctrl+F5", "Detach or attach Main Mixer"), ("Detach Rack", "Ctrl+F6", "Detach or attach Rack"),
            ("Play/stop", "Space", "Start or stop playback"), ("Stop", "Numpad0", "Stop playback"), ("Record", "Multiply", "Start recording"),
            ("Left locator", "Numpad1", "Move song position to left locator"), ("Right locator", "Numpad2", "Move song position to right locator"),
            ("Toggle loop", "L", "Turn sequencer loop on or off"), ("Metronome", "C", "Turn click on or off"),
            ("Quantize", "Ctrl+K", "Quantize selected notes or events"), ("Duplicate", "Ctrl+D", "Duplicate selection"), ("Join clips", "Ctrl+J", "Join selected clips")),

        P("Akai MPC Software", "Akai Professional", "DAW / Music", "MPC Software 2.x; shortcuts can vary with hardware mode", "https://www.akaipro.com/mpc-manuals",
            ("Play/stop", "Space", "Toggle sequence playback"), ("Play from start", "Shift+Space", "Play the sequence from its start"),
            ("Record", "Ctrl+R", "Enter record mode"), ("Overdub", "Ctrl+D", "Enter overdub mode"), ("Tap tempo", "T", "Tap the project tempo"),
            ("Undo", "Ctrl+Z", "Undo the last edit"), ("Redo", "Ctrl+Shift+Z", "Redo the last edit"), ("Save", "Ctrl+S", "Save the project"),
            ("Save As", "Ctrl+Shift+S", "Save the project under a new name"), ("Select all", "Ctrl+A", "Select all items in the focused editor"),
            ("Duplicate", "Ctrl+D", "Duplicate selected events"), ("Delete", "Delete", "Delete selected events"), ("Quantize", "Q", "Open or apply timing correction")),

        P("ACID Pro", "MAGIX", "DAW / Music", "ACID Pro 10–11 default Windows commands", "https://help.magix-hub.com/video/acid/en/",
            ("Play/stop", "Space", "Start or stop playback"), ("Play from start", "Shift+Space", "Play from the project start"), ("Record", "Ctrl+R", "Start recording"),
            ("Split event", "S", "Split selected event at cursor"), ("Create loop region", "R", "Create a region from the time selection"),
            ("Insert marker", "M", "Insert a marker at the cursor"), ("Insert tempo change", "T", "Insert a tempo/key/time-signature marker"),
            ("Quantize", "Ctrl+Q", "Quantize selected events"), ("Render As", "Ctrl+M", "Render the project"),
            ("Mix to new track", "Ctrl+Shift+M", "Mix the project to a new track"), ("Zoom to project", "F", "Fit the project timeline")),

        P("REAPER", "Cockos", "DAW / Music", "REAPER default Windows key map; actions are fully customizable", "https://www.reaper.fm/userguide.php",
            ("Play/stop", "Space", "Toggle playback"), ("Pause", "Ctrl+Space", "Pause playback"), ("Record", "Ctrl+R", "Start recording"),
            ("Split items", "S", "Split selected items at cursor"), ("Item properties", "F2", "Open item properties"), ("Track Manager", "Ctrl+Shift+M", "Open Track Manager"),
            ("Insert marker", "M", "Insert marker at current position"), ("Insert region", "Shift+R", "Create a region from time selection"),
            ("Toggle repeat", "R", "Toggle repeat/loop"), ("Metronome", "Ctrl+Shift+M", "Toggle metronome in some default maps"),
            ("Render", "Ctrl+Alt+R", "Open Render to File"), ("Action List", "Shift+/", "Open the Actions list")),

        P("Audacity", "Audacity Team", "Audio", "Audacity 3.x default Windows shortcuts", "https://manual.audacityteam.org/man/keyboard_shortcut_reference.html",
            ("Play/stop", "Space", "Start or stop playback"), ("Pause", "P", "Pause or resume"), ("Record", "R", "Start recording"),
            ("Append record", "Shift+R", "Record at the end of the selected track"), ("Loop play", "Shift+Space", "Loop the selected audio"),
            ("Split", "Ctrl+I", "Split clip at selection"), ("Silence audio", "Ctrl+L", "Replace selected audio with silence"),
            ("Trim audio", "Ctrl+T", "Remove audio outside selection"), ("New mono track", "Ctrl+Shift+N", "Add a new mono track"),
            ("Zoom in", "Ctrl+1", "Zoom in"), ("Zoom normal", "Ctrl+2", "Zoom to normal"), ("Zoom out", "Ctrl+3", "Zoom out"),
            ("Fit selection", "Ctrl+E", "Fit selection to width"), ("Fit project", "Ctrl+F", "Fit project to width")),

        P("OBS Studio", "OBS Project", "Streaming / Live Production", "Suggested paired bindings for OBS Studio 30/31. Assign the same combinations in Settings > Hotkeys before use.", "https://obsproject.com/kb/obs-studio-overview",
            ("Switch to scene / camera 1", "Ctrl+Alt+Shift+1", "Suggested binding; assign this key to the desired scene in OBS Hotkeys"),
            ("Switch to scene / camera 2", "Ctrl+Alt+Shift+2", "Suggested binding; assign this key to the desired scene in OBS Hotkeys"),
            ("Switch to scene / camera 3", "Ctrl+Alt+Shift+3", "Suggested binding; assign this key to the desired scene in OBS Hotkeys"),
            ("Switch to scene / camera 4", "Ctrl+Alt+Shift+4", "Suggested binding; assign this key to the desired scene in OBS Hotkeys"),
            ("Switch to scene / camera 5", "Ctrl+Alt+Shift+5", "Suggested binding; assign this key to the desired scene in OBS Hotkeys"),
            ("Switch to scene / camera 6", "Ctrl+Alt+Shift+6", "Suggested binding; assign this key to the desired scene in OBS Hotkeys"),
            ("Switch to scene / camera 7", "Ctrl+Alt+Shift+7", "Suggested binding; assign this key to the desired scene in OBS Hotkeys"),
            ("Switch to scene / camera 8", "Ctrl+Alt+Shift+8", "Suggested binding; assign this key to the desired scene in OBS Hotkeys"),
            ("Previous scene", "Ctrl+Alt+Shift+PageUp", "Suggested binding; assign this key to Previous Scene in OBS Hotkeys"),
            ("Next scene", "Ctrl+Alt+Shift+PageDown", "Suggested binding; assign this key to Next Scene in OBS Hotkeys"),
            ("Start/stop streaming", "Ctrl+Alt+Shift+S", "Suggested binding; assign this key to both Start and Stop Streaming in OBS Hotkeys"),
            ("Start/stop recording", "Ctrl+Alt+Shift+R", "Suggested binding; assign this key to both Start and Stop Recording in OBS Hotkeys"),
            ("Pause/resume recording", "Ctrl+Alt+Shift+P", "Suggested binding; assign this key to Pause/Unpause Recording in OBS Hotkeys"),
            ("Start/stop virtual camera", "Ctrl+Alt+Shift+V", "Suggested binding; assign this key to both Start and Stop Virtual Camera in OBS Hotkeys"),
            ("Studio Mode", "Ctrl+Alt+Shift+T", "Suggested binding; assign this key to Studio Mode in OBS Hotkeys"),
            ("Transition preview to program", "Ctrl+Alt+Shift+Enter", "Suggested binding; assign this key to Transition in OBS Hotkeys"),
            ("Mute/unmute microphone", "Ctrl+Alt+Shift+M", "Suggested binding; assign this key to the microphone source's Mute and Unmute actions"),
            ("Mute/unmute desktop audio", "Ctrl+Alt+Shift+D", "Suggested binding; assign this key to Desktop Audio's Mute and Unmute actions"),
            ("Show/hide camera source", "Ctrl+Alt+Shift+C", "Suggested binding; assign this key to the camera source's Show and Hide actions"),
            ("Save replay buffer", "Ctrl+Alt+Shift+L", "Suggested binding; assign this key to Save Replay in OBS Hotkeys")),

        P("Streamlabs Desktop", "Streamlabs", "Streaming / Live Production", "Suggested paired bindings. Assign the same combinations in Settings > Hotkeys before use.", "https://support.streamlabs.com/hc/en-us/articles/4413170379675-How-to-Set-up-Hotkeys-in-Streamlabs-Desktop",
            ("Switch to scene / camera 1", "Ctrl+Alt+Shift+1", "Suggested binding; assign this key to the desired scene in Streamlabs Hotkeys"),
            ("Switch to scene / camera 2", "Ctrl+Alt+Shift+2", "Suggested binding; assign this key to the desired scene in Streamlabs Hotkeys"),
            ("Switch to scene / camera 3", "Ctrl+Alt+Shift+3", "Suggested binding; assign this key to the desired scene in Streamlabs Hotkeys"),
            ("Switch to scene / camera 4", "Ctrl+Alt+Shift+4", "Suggested binding; assign this key to the desired scene in Streamlabs Hotkeys"),
            ("Switch to scene / camera 5", "Ctrl+Alt+Shift+5", "Suggested binding; assign this key to the desired scene in Streamlabs Hotkeys"),
            ("Switch to scene / camera 6", "Ctrl+Alt+Shift+6", "Suggested binding; assign this key to the desired scene in Streamlabs Hotkeys"),
            ("Switch to scene / camera 7", "Ctrl+Alt+Shift+7", "Suggested binding; assign this key to the desired scene in Streamlabs Hotkeys"),
            ("Switch to scene / camera 8", "Ctrl+Alt+Shift+8", "Suggested binding; assign this key to the desired scene in Streamlabs Hotkeys"),
            ("Previous scene", "Ctrl+Alt+Shift+PageUp", "Suggested binding; assign this key to the previous-scene action"),
            ("Next scene", "Ctrl+Alt+Shift+PageDown", "Suggested binding; assign this key to the next-scene action"),
            ("Start/stop streaming", "Ctrl+Alt+Shift+S", "Suggested binding; assign this key to start and stop streaming"),
            ("Start/stop recording", "Ctrl+Alt+Shift+R", "Suggested binding; assign this key to start and stop recording"),
            ("Mute/unmute microphone", "Ctrl+Alt+Shift+M", "Suggested binding; assign this key to mute and unmute the microphone"),
            ("Mute/unmute desktop audio", "Ctrl+Alt+Shift+D", "Suggested binding; assign this key to mute and unmute desktop audio"),
            ("Show/hide camera source", "Ctrl+Alt+Shift+C", "Suggested binding; assign this key to show and hide the camera source"),
            ("Save replay", "Ctrl+Alt+Shift+L", "Suggested binding; assign this key to Save Replay"),
            ("Skip alert", "Ctrl+Alt+Shift+K", "Suggested binding; assign this key to Skip Alert")),

        P("vMix", "StudioCoast", "Streaming / Live Production", "Suggested paired bindings for vMix 28/29. Assign the same combinations in Settings > Shortcuts and select the corresponding function/input.", "https://www.vmix.com/help29/KeyboardShortcuts.html",
            ("Cut directly to input / camera 1", "Ctrl+Alt+Shift+1", "Suggested binding; create a vMix shortcut using CutDirect and Input 1"),
            ("Cut directly to input / camera 2", "Ctrl+Alt+Shift+2", "Suggested binding; create a vMix shortcut using CutDirect and Input 2"),
            ("Cut directly to input / camera 3", "Ctrl+Alt+Shift+3", "Suggested binding; create a vMix shortcut using CutDirect and Input 3"),
            ("Cut directly to input / camera 4", "Ctrl+Alt+Shift+4", "Suggested binding; create a vMix shortcut using CutDirect and Input 4"),
            ("Cut directly to input / camera 5", "Ctrl+Alt+Shift+5", "Suggested binding; create a vMix shortcut using CutDirect and Input 5"),
            ("Cut directly to input / camera 6", "Ctrl+Alt+Shift+6", "Suggested binding; create a vMix shortcut using CutDirect and Input 6"),
            ("Cut directly to input / camera 7", "Ctrl+Alt+Shift+7", "Suggested binding; create a vMix shortcut using CutDirect and Input 7"),
            ("Cut directly to input / camera 8", "Ctrl+Alt+Shift+8", "Suggested binding; create a vMix shortcut using CutDirect and Input 8"),
            ("Previous preview input", "Ctrl+Alt+Shift+PageUp", "Suggested binding; create a vMix shortcut for the previous preview input"),
            ("Next preview input", "Ctrl+Alt+Shift+PageDown", "Suggested binding; create a vMix shortcut for the next preview input"),
            ("Cut preview to output", "Ctrl+Alt+Shift+Enter", "Suggested binding; create a vMix shortcut using Cut"),
            ("Fade to black", "Ctrl+Alt+Shift+F", "Suggested binding; create a vMix shortcut using FadeToBlack"),
            ("Start/stop streaming", "Ctrl+Alt+Shift+S", "Suggested binding; create vMix shortcuts for StartStreaming and StopStreaming"),
            ("Start/stop recording", "Ctrl+Alt+Shift+R", "Suggested binding; create vMix shortcuts for StartRecording and StopRecording"),
            ("Start/stop external output", "Ctrl+Alt+Shift+V", "Suggested binding; create vMix shortcuts for the external or virtual-camera output"),
            ("Mute/unmute microphone input", "Ctrl+Alt+Shift+M", "Suggested binding; create a vMix AudioOn/AudioOff shortcut for the microphone input"),
            ("Toggle overlay 1", "Ctrl+Alt+Shift+O", "Suggested binding; create a vMix shortcut for OverlayInput1In/Out")),

        P("XSplit Broadcaster", "SplitmediaLabs", "Streaming / Live Production", "Suggested paired bindings. Assign the same combinations in Tools > Settings > Hotkeys before use.", "https://support.xsplit.com/en/article/settings-9b70rh/",
            ("Switch to scene / camera 1", "Ctrl+Alt+Shift+1", "Suggested binding; assign this key to scene 1 in XSplit Hotkeys"),
            ("Switch to scene / camera 2", "Ctrl+Alt+Shift+2", "Suggested binding; assign this key to scene 2 in XSplit Hotkeys"),
            ("Switch to scene / camera 3", "Ctrl+Alt+Shift+3", "Suggested binding; assign this key to scene 3 in XSplit Hotkeys"),
            ("Switch to scene / camera 4", "Ctrl+Alt+Shift+4", "Suggested binding; assign this key to scene 4 in XSplit Hotkeys"),
            ("Switch to scene / camera 5", "Ctrl+Alt+Shift+5", "Suggested binding; assign this key to scene 5 in XSplit Hotkeys"),
            ("Switch to scene / camera 6", "Ctrl+Alt+Shift+6", "Suggested binding; assign this key to scene 6 in XSplit Hotkeys"),
            ("Switch to scene / camera 7", "Ctrl+Alt+Shift+7", "Suggested binding; assign this key to scene 7 in XSplit Hotkeys"),
            ("Switch to scene / camera 8", "Ctrl+Alt+Shift+8", "Suggested binding; assign this key to scene 8 in XSplit Hotkeys"),
            ("Previous scene", "Ctrl+Alt+Shift+PageUp", "Suggested binding; assign this key to Previous Scene"),
            ("Next scene", "Ctrl+Alt+Shift+PageDown", "Suggested binding; assign this key to Next Scene"),
            ("Start/stop broadcast", "Ctrl+Alt+Shift+S", "Suggested binding; assign this key to start and stop broadcasting"),
            ("Start/stop recording", "Ctrl+Alt+Shift+R", "Suggested binding; assign this key to start and stop recording"),
            ("Mute/unmute microphone", "Ctrl+Alt+Shift+M", "Suggested binding; assign this key to microphone mute/unmute"),
            ("Mute/unmute system sound", "Ctrl+Alt+Shift+D", "Suggested binding; assign this key to system-sound mute/unmute"),
            ("Show/hide camera source", "Ctrl+Alt+Shift+C", "Suggested binding; assign this key to the camera source's visibility action"),
            ("Take screenshot", "Ctrl+Alt+Shift+P", "Suggested binding; assign this key to the screenshot action")),

        P("Wirecast", "Telestream", "Streaming / Live Production", "Suggested paired bindings. Assign the same combinations in Preferences > Shortcuts or Document Hotkeys before use.", "https://www.telestream.net/pdfs/technical/Wirecast-Shortcuts-Hotkeys-Resource-Guide.pdf",
            ("Select shot / camera 1", "Ctrl+Alt+Shift+1", "Suggested binding; assign this document hotkey to shot 1 in Wirecast"),
            ("Select shot / camera 2", "Ctrl+Alt+Shift+2", "Suggested binding; assign this document hotkey to shot 2 in Wirecast"),
            ("Select shot / camera 3", "Ctrl+Alt+Shift+3", "Suggested binding; assign this document hotkey to shot 3 in Wirecast"),
            ("Select shot / camera 4", "Ctrl+Alt+Shift+4", "Suggested binding; assign this document hotkey to shot 4 in Wirecast"),
            ("Select shot / camera 5", "Ctrl+Alt+Shift+5", "Suggested binding; assign this document hotkey to shot 5 in Wirecast"),
            ("Select shot / camera 6", "Ctrl+Alt+Shift+6", "Suggested binding; assign this document hotkey to shot 6 in Wirecast"),
            ("Select shot / camera 7", "Ctrl+Alt+Shift+7", "Suggested binding; assign this document hotkey to shot 7 in Wirecast"),
            ("Select shot / camera 8", "Ctrl+Alt+Shift+8", "Suggested binding; assign this document hotkey to shot 8 in Wirecast"),
            ("Previous shot", "Ctrl+Alt+Shift+PageUp", "Suggested binding; assign this key to a previous-shot command or document hotkey"),
            ("Next shot", "Ctrl+Alt+Shift+PageDown", "Suggested binding; assign this key to a next-shot command or document hotkey"),
            ("Go / take shot live", "Ctrl+Alt+Shift+Enter", "Suggested binding; assign this key to Go"),
            ("Toggle AutoLive", "Ctrl+Alt+Shift+T", "Suggested binding; assign this key to AutoLive"),
            ("Start/stop broadcast", "Ctrl+Alt+Shift+S", "Suggested binding; assign this key to start and stop broadcasting"),
            ("Start/stop recording", "Ctrl+Alt+Shift+R", "Suggested binding; assign this key to start and stop recording"),
            ("Mute/unmute microphone", "Ctrl+Alt+Shift+M", "Suggested binding; assign this key to the microphone mute action")),

        P("Visual Studio Code", "Microsoft", "Development", "Current default Windows keybindings", "https://code.visualstudio.com/docs/reference/default-keybindings",
            ("Command Palette", "Ctrl+Shift+P", "Show all commands"), ("Quick Open", "Ctrl+P", "Quickly open a file"), ("New window", "Ctrl+Shift+N", "Open a new window"),
            ("Close editor", "Ctrl+W", "Close active editor"), ("Reopen closed editor", "Ctrl+Shift+T", "Reopen the last closed editor"),
            ("Go to line", "Ctrl+G", "Go to a line number"), ("Go to symbol", "Ctrl+Shift+O", "Go to a symbol in the current file"),
            ("Go to definition", "F12", "Open definition"), ("Peek definition", "Alt+F12", "Peek definition inline"), ("Rename symbol", "F2", "Rename symbol"),
            ("Format document", "Shift+Alt+F", "Format the active document"), ("Toggle terminal", "Ctrl+`", "Show or hide integrated terminal"),
            ("New terminal", "Ctrl+Shift+`", "Create an integrated terminal"), ("Toggle sidebar", "Ctrl+B", "Show or hide primary sidebar"),
            ("Zen Mode", "Ctrl+K", "Start the Zen Mode chord; press Z next"), ("Run task", "Ctrl+Shift+B", "Run the configured build task"),
            ("Start debugging", "F5", "Start or continue debugging"), ("Step over", "F10", "Step over in debugger"), ("Step into", "F11", "Step into in debugger")),

        P("VLC media player", "VideoLAN", "Media", "VLC 3.x default Windows hotkeys", "https://docs.videolan.me/vlc-user/desktop/3.0/en/basic/hotkeys.html",
            ("Play/pause", "Space", "Toggle playback"), ("Stop", "S", "Stop playback"), ("Next", "N", "Next playlist item"), ("Previous", "P", "Previous playlist item"),
            ("Fullscreen", "F", "Toggle fullscreen"), ("Exit fullscreen", "Escape", "Leave fullscreen"), ("Mute", "M", "Toggle mute"),
            ("Volume up", "Ctrl+Up", "Increase volume"), ("Volume down", "Ctrl+Down", "Decrease volume"),
            ("Short jump forward", "Alt+Right", "Jump forward a short interval"), ("Short jump backward", "Alt+Left", "Jump backward a short interval"),
            ("Faster", "Shift+=", "Increase playback speed"), ("Slower", "-", "Decrease playback speed"), ("Normal speed", "=", "Restore normal playback speed"),
            ("Audio track", "B", "Cycle audio tracks"), ("Subtitle track", "V", "Cycle subtitle tracks"), ("Playlist", "Ctrl+L", "Show or hide playlist")),

        P("Notepad++", "Notepad++ Team", "Text editor", "Notepad++ 8.x defaults; Shortcut Mapper can customize these", "https://npp-user-manual.org/docs/keyboard/",
            ("New file", "Ctrl+N", "Create a new file"), ("Open file", "Ctrl+O", "Open a file"), ("Save all", "Ctrl+Shift+S", "Save all open files"),
            ("Close all", "Ctrl+Shift+W", "Close all open files"), ("Find in files", "Ctrl+Shift+F", "Search files"), ("Replace", "Ctrl+H", "Open Replace"),
            ("Go to line", "Ctrl+G", "Go to a line"), ("Duplicate line", "Ctrl+D", "Duplicate current line"), ("Delete line", "Ctrl+L", "Delete current line"),
            ("Move line up", "Ctrl+Shift+Up", "Move current line upward"), ("Move line down", "Ctrl+Shift+Down", "Move current line downward"),
            ("Toggle comment", "Ctrl+Q", "Toggle line comment"), ("Block comment", "Ctrl+Shift+Q", "Toggle block comment"),
            ("Fold all", "Alt+0", "Collapse all folds"), ("Unfold all", "Alt+Shift+0", "Expand all folds"),
            ("Next document", "Ctrl+Tab", "Switch to next document"), ("Previous document", "Ctrl+Shift+Tab", "Switch to previous document"))
    ];

    private static ApplicationShortcutProfile P(string name, string publisher, string category,
        string versionNote, string sourceUrl, params (string Name, string Shortcut, string Description)[] shortcuts) =>
        new(name, publisher, category, versionNote, sourceUrl,
            shortcuts.Select(item => new ApplicationShortcut("Commands", item.Name, item.Shortcut, item.Description)).ToArray());
}
